apiVersion: v1
kind: Service
metadata:
  name: demo-emp-fe-lb
  namespace: demo-emp
spec:
  selector:
    app: emp-fe-pods
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  