apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-fe-dp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emp-fe-pods
  template:
    metadata:
      labels:
        app: emp-fe-pods
    spec:
      imagePullSecrets:
        name: docker-creds
      containers:
        - name: emp-fe-con
          image: demo-emp-fe:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80