apiVersion: v1
kind: Secret
metadata:
  name: backend-sc
  namespace: demo-emp
type: Opeque
data:
  MYSQL_USER: ZW1wbG95ZWUtYWRtaW4=
  MYSQL_PASSWORD: VXNlcjEyMw==
  MYSQL_DATABASE: ZW1wbG95ZWUtbWFuYWdlbWVudA==
  jwt-token: bXlTdXBlclNlY3JldEtleTEyMzQ1Njc4OQ==