apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-emp-db-volc  # name of the PVC
  namespace: demo-emp 
spec:
  accessModes:
    - ReadWriteOnce  # mentioning the access case as ReadWriteOnce
  #volumeName: employee-db-volume # name of the already PV created 
  storageClassName: "" # Mentioned to not to use the default storageclass
  resources:
    requests:
      storage: 1Gi # claiming 1Gi space from the PV