apiVersion: v1
kind: Secret
metadata:
  name: demo-employee-secret  # reference name of the secrtes 
  namespace: demo-emp
type: Opeque #
data:  # this is used if values aren't base64 encoded (i.e text values)
  MYSQL_ROOT_PASSWORD: QWRtaW4xMjM=
  MYSQL_USER: ZW1wbG95ZWUtYWRtaW4=
  MYSQL_PASSWORD: VXNlcjEyMw==
  MYSQL_DATABASE: ZW1wbG95ZWUtbWFuYWdlbWVudA==