apiVersion: v1
kind: Secret
metadata:
  name: demo-employee-secret  # reference name of the secrtes 
type: Opeque #
stringData:  # this is used if values aren't base64 encoded (i.e text values)
  MYSQL_ROOT_PASSWORD: Admin123
  MYSQL_USER: employee-admin
  MYSQL_PASSOWRD: User123
  MYSQL_DATABASE: employee_management